chore(Makefile): add make target `sign-archive`
Usage: make sign-archive checksum=<sha256-checksum>
Designed use case is to download latest build from bintray to package/archive/, verify the zip archive with sha256-checksum and sign the archive in generated appcast.xml.

diff --git a/package/create_archive b/package/create_archive
--- a/package/create_archive
+++ b/package/create_archive
@@ -20,13 +20,23 @@ if [ -n "${testing}" ]; then
     rm -f "${target_archive}" > /dev/null 2>&1 || true
 fi
 
-if [ -e "${target_archive}" ]; then
-  echo "ERROR: target archive already exists: ${target_archive}"
-  exit 1
+if [ -n "${checksum}" ]; then
+    if ! [ -f "${target_archive}" ]; then
+        echo >&2 "ERROR: file does not exit: ${target_archive}"
+        exit 1
+    fi
+    echo 'sha256 checksum:'
+    echo "${checksum}  ${target_archive}"
+    shasum -a 256 -c <<<"${checksum}  ${target_archive}"
+else
+    if [ -e "${target_archive}" ]; then
+        echo >&2 "ERROR: target archive already exists: ${target_archive}"
+        exit 1
+    fi
+    zip -r "${target_archive}" Squirrel.pkg
+    echo 'sha256 checksum:'
+    shasum -a 256 "${target_archive}"
 fi
-
-zip -r "${target_archive}" Squirrel.pkg
-
 dsa_signature=$(ruby sign/sign_update.rb "${target_archive}" sign/dsa_priv.pem)
 file_length=$(stat -f%z "${target_archive}")
 pub_date=$(date -R)
